# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  font: serif

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal Website of Yifan Zhang, Economics, Political Economy, Development Economics, Economic History, Kellogg School of Management, Northwestern University'
    twitter: 'TedZhang1996'
  analytics:
    google_analytics: 'G-T0C5J86LTE'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: "Yifan Zhang"
      filename: ""

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Yifan Zhang. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

i_am_a_sponsor: true
